name: cer-qa
channels:
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip
  - pip:
    - wheel==0.37.0
    - PyPDF2==1.26.0
    - tika==1.24
    - python-dotenv==0.19.2
    - fitz==0.0.1.dev2
    - pandas==1.3.4
    - beautifulsoup4==4.10.0
    - nltk==3.6.5
    - scikit-learn==1.0.1
    - transformers==4.6.1
    - tqdm==4.62.3
    - numpy==1.21.4
    - spacy==3.2.0
    - fuzzywuzzy==0.18.0
    - ipython==7.30.0
    - fastapi==0.70.0
    - streamlit==1.2.0
    - farm-haystack==0.10.0
    - uvicorn==0.15.0
    - torch==1.8.1
    - torchvision==0.9.1
    - torchaudio==0.8.1